/*
 * Accounts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kyriba.sample.model;

import com.fasterxml.jackson.databind.JavaType;
import com.google.common.reflect.TypeToken;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import com.kyriba.sample.model.accounts.AccountSearchModel;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * PageOfSearchModels
 */

public class PageOfSearchModel<T>{
    @SerializedName("metadata")
    private Metadata metadata = null;

    @SerializedName("results")
    private List<T> results = null;

    private T type;

    public PageOfSearchModel<T> metadata(Metadata metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get metadata
     * @return metadata
     **/
    @ApiModelProperty(value = "")
    public Metadata getMetadata() {
        return metadata;
    }

    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    public PageOfSearchModel<T> results(List<T> results) {
        this.results = results;
        return this;
    }

    public PageOfSearchModel<T> addResultsItem(T resultsItem) {
        if (this.results == null) {
            this.results = new ArrayList<T>();
        }
        this.results.add(resultsItem);
        return this;
    }

    /**
     * Get results
     * @return results
     **/
    @ApiModelProperty(value = "")
    public List<T> getResults() {
        return results;
    }

    public void setResults(List<T> results) {
        this.results = results;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PageOfSearchModel<T> pageOfSearchModel = (PageOfSearchModel<T>) o;
        return Objects.equals(this.metadata, pageOfSearchModel.metadata) &&
                Objects.equals(this.results, pageOfSearchModel.results);
    }

    @Override
    public int hashCode() {
        return Objects.hash(metadata, results);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PageOfAccountSearchModel {\n");

        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("    results: ").append(toIndentedString(results)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}