/*
 * Accounts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kyriba.sample.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.UUID;

/**
 * Represents possible identifiers for resource. Should be provided at least one identifier (code or uuid). In the case of providing uuid and code, uuid will be used for resolving the reference.
 */
@ApiModel(description = "Represents possible identifiers for resource. Should be provided at least one identifier (code or uuid). In the case of providing uuid and code, uuid will be used for resolving the reference.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-13T11:35:10.236Z")
public class ReferenceModel {
  @SerializedName("code")
  private String code = null;

  @SerializedName("uuid")
  private UUID uuid = null;

  public ReferenceModel code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Code identifier.
   * @return code
  **/
  @ApiModelProperty(example = "CODE_ID", value = "Code identifier.")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ReferenceModel uuid(UUID uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * UUID identifier. Has priority over the code
   * @return uuid
  **/
  @ApiModelProperty(example = "123e4567-e89b-12d3-a456-426655440001", value = "UUID identifier. Has priority over the code")
  public UUID getUuid() {
    return uuid;
  }

  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferenceModel referenceModel = (ReferenceModel) o;
    return Objects.equals(this.code, referenceModel.code) &&
        Objects.equals(this.uuid, referenceModel.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferenceModel {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

