/*
 * Accounts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kyriba.sample.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;
import java.util.UUID;

/**
 * ResponseIdModel
 */
public class ResponseIdModel {
    @SerializedName("code")
    private String code = null;

    @SerializedName("uuid")
    private UUID uuid = null;

    public ResponseIdModel code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Code of the resource.
     *
     * @return code
     **/
    @ApiModelProperty(example = "MY_RESOURCE_CODE", required = true, value = "Code of the resource.")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public ResponseIdModel uuid(UUID uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * UUID of the created resource.
     *
     * @return uuid
     **/
    @ApiModelProperty(example = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", required = true, value = "UUID of the created resource.")
    public UUID getUuid() {
        return uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResponseIdModel responseIdModel = (ResponseIdModel) o;
        return Objects.equals(this.code, responseIdModel.code) &&
                Objects.equals(this.uuid, responseIdModel.uuid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, uuid);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ResponseIdModel {\n");

        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

