/*
 * Accounts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kyriba.sample.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * REST API Error.
 */
@ApiModel(description = "REST API Error.")
public class RestApiError {
    @SerializedName("code")
    private String code = null;

    @SerializedName("details")
    private List<RestApiError> details = null;

    @SerializedName("innererror")
    private InnerError innererror = null;

    @SerializedName("message")
    private String message = null;

    @SerializedName("target")
    private String target = null;

    public RestApiError code(String code) {
        this.code = code;
        return this;
    }

    /**
     * One of a server-defined set of error codes.
     *
     * @return code
     **/
    @ApiModelProperty(example = "Invalid", required = true, value = "One of a server-defined set of error codes.")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public RestApiError details(List<RestApiError> details) {
        this.details = details;
        return this;
    }

    public RestApiError addDetailsItem(RestApiError detailsItem) {
        if (this.details == null) {
            this.details = new ArrayList<RestApiError>();
        }
        this.details.add(detailsItem);
        return this;
    }

    /**
     * An array of details about specific errors that led to this reported error.
     *
     * @return details
     **/
    @ApiModelProperty(example = "[{\"code\":\"Invalid\",\"message\":\"must not be blank\",\"target\":\"target\"}]", value = "An array of details about specific errors that led to this reported error.")
    public List<RestApiError> getDetails() {
        return details;
    }

    public void setDetails(List<RestApiError> details) {
        this.details = details;
    }

    public RestApiError innererror(InnerError innererror) {
        this.innererror = innererror;
        return this;
    }

    /**
     * An object containing more specific information than the current object about the error.
     *
     * @return innererror
     **/
    @ApiModelProperty(value = "An object containing more specific information than the current object about the error.")
    public InnerError getInnererror() {
        return innererror;
    }

    public void setInnererror(InnerError innererror) {
        this.innererror = innererror;
    }

    public RestApiError message(String message) {
        this.message = message;
        return this;
    }

    /**
     * A human-readable representation of the error.
     *
     * @return message
     **/
    @ApiModelProperty(example = "The request failed because it contained invalid values", required = true, value = "A human-readable representation of the error.")
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public RestApiError target(String target) {
        this.target = target;
        return this;
    }

    /**
     * The target of the error.
     *
     * @return target
     **/
    @ApiModelProperty(example = "target", value = "The target of the error.")
    public String getTarget() {
        return target;
    }

    public void setTarget(String target) {
        this.target = target;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RestApiError restApiError = (RestApiError) o;
        return Objects.equals(this.code, restApiError.code) &&
                Objects.equals(this.details, restApiError.details) &&
                Objects.equals(this.innererror, restApiError.innererror) &&
                Objects.equals(this.message, restApiError.message) &&
                Objects.equals(this.target, restApiError.target);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, details, innererror, message, target);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RestApiError {\n");

        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    details: ").append(toIndentedString(details)).append("\n");
        sb.append("    innererror: ").append(toIndentedString(innererror)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    target: ").append(toIndentedString(target)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

