server:
  port: 5000

client:
  id: ${CLIENT_ID}
  secret: ${CLIENT_SECRET}

access:
  token:
    url: https://demo.kyriba.com/gateway/oauth/token

base:
  api:
    name: banks
  url: https://demo.kyriba.com/gateway/api

request:
  mapping: /v1/${base.api.name}

spring:
  profiles:
    active: ${base.api.name}




