api:
  filters:
    - code
    - uuid
    - interfaceCode
    - description
    - firstName
    - lastName
    - email
    - ssoIdentity
    - accessProfile.uuid
    - accessProfile.code
    - dataPermissionProfile.uuid
    - dataPermissionProfile.code
    - companyOwnership.uuid
    - companyOwnership.code
    - paymentAdministrator
    - systemAdministrator
    - emailRecipient