server:
  port: 5000

client:
  id: ${CLIENT_ID}
  secret: ${CLIENT_SECRET}

access:
  token:
    url: https://demo.kyriba.com/gateway/oauth/token

base:
  url: https://demo.kyriba.com/gateway/api


#List of available API
list:
  apis:
    - /v1/accounts
    - /v1/bank-branches
    - /v1/bank-groups
    - /v1/banks
    - /v1/companies
    - /v1/users

#Lists of columns that can be used for filtering and sorting.
api:
  filters:
    /v1/accounts:
      - code
      - uuid
      - description
      - company.uuid
      - company.code
      - branch.uuid
      - branch.code
      - bank.uuid
      - bank.code
      - currency.uuid
      - currency.code
      - countryCode
      - accountType
      - banCode
      - creationDate
      - updateDate
      - closingDate
      - activeStatus
      - statementIdentifier
      - accountAvailableForPayments

    /v1/bank-branches:
      - code
      - uuid
      - description
      - bank.code
      - bank.uuid
      - address.country.code
      - address.country.uuid
      - bic

    /v1/bank-groups:
      - code
      - uuid
      - description
      - leader.uuid
      - leader.code
      - intermediary
      - counterparty

    /v1/banks:
      - code
      - uuid
      - description
      - defaultGroup.uuid
      - defaultGroup.code
      - countryCode
      - intercompany

    /v1/companies:
      - code
      - uuid
      - description1
      - description2
      - shortCode
      - interfaceCode
      - defaultGroup.uuid
      - defaultGroup.code
      - businessIdentifiers.otherIdentifierType
      - businessIdentifiers.otherIdentifierValue
      - address.country.code
      - address.country.uuid

    /v1/users:
      - code
      - uuid
      - interfaceCode
      - description
      - firstName
      - lastName
      - email
      - ssoIdentity
      - accessProfile.uuid
      - accessProfile.code
      - dataPermissionProfile.uuid
      - dataPermissionProfile.code
      - companyOwnership.uuid
      - companyOwnership.code
      - paymentAdministrator
      - systemAdministrator
      - emailRecipient

#Lists of available values for some columns from filters.
enums:
  available:
    values:
      /v1/accounts:
        accountType:
          - BANK_ACCOUNT
          - INTERCOMPANY_ACCOUNT
          - OTHER_ACCOUNT
          - SHARED_ACCOUNT
        activeStatus:
          - OPENED
          - CLOSED
        accountAvailableForPayments:
          - true
          - false


      /v1/bank-groups:
        intermediary:
          - true
          - false
        counterparty:
          - true
          - false

      /v1/banks:
        intercompany:
          - true
          - false

      /v1/users:
        paymentAdministrator:
          - true
          - false
        systemAdministrator:
          - true
          - false
        emailRecipient:
          - true
          - false
