/*
 * Accounts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ReferenceModel;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * AmountModel_
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-13T11:35:10.236Z")
public class AmountModel_ {
  @SerializedName("currency")
  private ReferenceModel currency = null;

  @SerializedName("value")
  private BigDecimal value = null;

  public AmountModel_ currency(ReferenceModel currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Amount currency.
   * @return currency
  **/
  @ApiModelProperty(value = "Amount currency.")
  public ReferenceModel getCurrency() {
    return currency;
  }

  public void setCurrency(ReferenceModel currency) {
    this.currency = currency;
  }

  public AmountModel_ value(BigDecimal value) {
    this.value = value;
    return this;
  }

   /**
   * Amount value.
   * minimum: 0
   * @return value
  **/
  @ApiModelProperty(example = "1.123456", value = "Amount value.")
  public BigDecimal getValue() {
    return value;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AmountModel_ amountModel_ = (AmountModel_) o;
    return Objects.equals(this.currency, amountModel_.currency) &&
        Objects.equals(this.value, amountModel_.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AmountModel_ {\n");
    
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

