/*
 * Accounts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Links
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-13T11:35:10.236Z")
public class Links {
  @SerializedName("current")
  private String current = null;

  @SerializedName("next")
  private String next = null;

  @SerializedName("prev")
  private String prev = null;

  public Links current(String current) {
    this.current = current;
    return this;
  }

   /**
   * Current page.
   * @return current
  **/
  @ApiModelProperty(example = "https://host/gateway/api/resources?page.limit=10&page.offset=10", value = "Current page.")
  public String getCurrent() {
    return current;
  }

  public void setCurrent(String current) {
    this.current = current;
  }

  public Links next(String next) {
    this.next = next;
    return this;
  }

   /**
   * Next page.
   * @return next
  **/
  @ApiModelProperty(example = "https://host/gateway/api/resources?page.limit=10&page.offset=20", value = "Next page.")
  public String getNext() {
    return next;
  }

  public void setNext(String next) {
    this.next = next;
  }

  public Links prev(String prev) {
    this.prev = prev;
    return this;
  }

   /**
   * Previous page.
   * @return prev
  **/
  @ApiModelProperty(example = "https://host/gateway/api/resources?page.limit=10&page.offset=0", value = "Previous page.")
  public String getPrev() {
    return prev;
  }

  public void setPrev(String prev) {
    this.prev = prev;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Links links = (Links) o;
    return Objects.equals(this.current, links.current) &&
        Objects.equals(this.next, links.next) &&
        Objects.equals(this.prev, links.prev);
  }

  @Override
  public int hashCode() {
    return Objects.hash(current, next, prev);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Links {\n");
    
    sb.append("    current: ").append(toIndentedString(current)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    prev: ").append(toIndentedString(prev)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

