/*
 * Accounts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * PageOfSearchModels
 */

public class PageOfAccountSearchModel {
    @SerializedName("metadata")
    private Metadata metadata = null;

    @SerializedName("results")
    private List<AccountSearchModel> results = null;

    public PageOfAccountSearchModel metadata(Metadata metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get metadata
     * @return metadata
     **/
    @ApiModelProperty(value = "")
    public Metadata getMetadata() {
        return metadata;
    }

    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    public PageOfAccountSearchModel results(List<AccountSearchModel> results) {
        this.results = results;
        return this;
    }

    public PageOfAccountSearchModel addResultsItem(AccountSearchModel resultsItem) {
        if (this.results == null) {
            this.results = new ArrayList<AccountSearchModel>();
        }
        this.results.add(resultsItem);
        return this;
    }

    /**
     * Get results
     * @return results
     **/
    @ApiModelProperty(value = "")
    public List<AccountSearchModel> getResults() {
        return results;
    }

    public void setResults(List<AccountSearchModel> results) {
        this.results = results;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PageOfAccountSearchModel pageOfAccountSearchModel = (PageOfAccountSearchModel) o;
        return Objects.equals(this.metadata, pageOfAccountSearchModel.metadata) &&
                Objects.equals(this.results, pageOfAccountSearchModel.results);
    }

    @Override
    public int hashCode() {
        return Objects.hash(metadata, results);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PageOfAccountSearchModel {\n");

        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("    results: ").append(toIndentedString(results)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}